Repository transhumandesign/kag-base, pull requests merged in 2024-12, with the labels that each got.

#2222 [changed] Infinite ammo count is shown in singleplayer
  Entities/Vehicles/Common/VehicleGUI.as
Labels: no functional change, ready

#2153 Heads for Vamist and GoldenGuy
  Entities/Characters/Sprites/CustomHeads/GoldenGuy.png
  Entities/Characters/Sprites/CustomHeads/Vamist.png
  Rules/CommonScripts/accolade_data.cfg
Labels: no functional change, ready

#2176 [changed] Improved Ladder's sprite
  Entities/Structures/Ladder/Ladder.png
Labels: no functional change, ready

#2226 [fixed] Catapult couldn't fire properly in offline
  Entities/Vehicles/Catapult/Catapult.as
Labels: ready, fix

#2150 Head update (TheCustomerMan, appropriate signature)
  Entities/Characters/Sprites/CustomHeads/TheCustomerMan.png
Labels: ready

#2069 [fixed] Builder Queued Hit Fix
  Entities/Characters/Builder/BuilderLogic.as
Labels: ready, fix

#2151 [fix] Changed TheCustomerMan signature
  Entities/Characters/Sprites/CustomHeads/RogueCupcake.png
Labels: ready

#2174 [fixed] Sponge will change team when picked up
  Entities/Items/Sponge/Sponge.cfg
Labels: ready

#2125 [fixed] camera zoom in spectator doesnt using action keys
  Rules/CommonScripts/Spectator.as
Labels: ready, fix

#2169 [fixed] don't pick up your own shot arrows from mid air
  Entities/Characters/Archer/ArcherLogic.as
Labels: ready

#2217 [fixed] Airship & Bomber issues
  Entities/Vehicles/Airships/Airship.cfg
  Entities/Vehicles/Airships/Bomber.cfg
Labels: ready, Sandbox

#1889 [fixed] Fishy airdrown gets reverted in water over time
  Entities/Natural/Animals/Scripts/AirDrown.as
Labels: change

#1761 Scripted playernames.
  Rules/CTF/gamemode.cfg
  Rules/CommonScripts/PlayerNames.as
  Rules/Sandbox/gamemode.cfg
  Rules/Simple/gamemode.cfg
  Rules/SmallCTF/gamemode.cfg
  Rules/TDM/gamemode.cfg
  Rules/WAR/gamemode.cfg
Labels: change, engine change, ready

#2186 [fixed] Couldn't swap ballista ammo in offline
  Entities/Vehicles/Common/Vehicle.as
Labels: ready, fix

#2227 [fixed] Princess didn't make heart anim in online
  Entities/Characters/Princess/Princess.cfg
  Entities/Characters/Princess/PrincessAnim.as
  Entities/Characters/Princess/PrincessBrain.as
  Entities/Characters/Princess/PrincessLogic.as
Labels: ready, fix

#2219 [fixed] mechanisms
  Entities/Structures/Common/DummyCommon.as
  Entities/Structures/Common/DummyGrid.as
  Entities/Structures/Common/DummyOnStatic.as
  Entities/Structures/Components/GenericComponent.as
  Entities/Structures/Components/Load/Bolter/Bolter.as
  Entities/Structures/Components/Load/Dispenser/Dispenser.as
  Entities/Structures/Components/Load/Lamp/Lamp.as
  Entities/Structures/Components/Load/Obstructor/Obstructor.as
  Entities/Structures/Components/Load/Obstructor/Obstructor.cfg
  Entities/Structures/Components/Load/Obstructor/Obstructor.png
  Entities/Structures/Components/Load/Spiker/GenericSpike.as
  Entities/Structures/Components/Load/Spiker/Spike.cfg
  Entities/Structures/Components/Load/Spiker/Spiker.as
  Entities/Structures/Components/Passive/Diode/Diode.as
  Entities/Structures/Components/Passive/Emitter/Emitter.as
  Entities/Structures/Components/Passive/Inverter/Inverter.as
  Entities/Structures/Components/Passive/Junction/Junction.as
  Entities/Structures/Components/Passive/Magazine/Magazine.as
  Entities/Structures/Components/Passive/Oscillator/Oscillator.as
  Entities/Structures/Components/Passive/Randomizer/Randomizer.as
  Entities/Structures/Components/Passive/Receiver/Receiver.as
  Entities/Structures/Components/Passive/Resistor/Resistor.as
  Entities/Structures/Components/Passive/Toggle/Toggle.as
  Entities/Structures/Components/Passive/Transistor/Transistor.as
  Entities/Structures/Components/Passive/Wire/Wire.as
  Entities/Structures/Components/Source/CoinSlot/CoinSlot.as
  Entities/Structures/Components/Source/Lever/Lever.as
  Entities/Structures/Components/Source/PressurePlate/PressurePlate.as
  Entities/Structures/Components/Source/PushButton/PushButton.as
  Entities/Structures/Components/Source/Sensor/Sensor.as
  Entities/Structures/Components/Source/Sensor/Sensor.cfg
  Rules/Challenge/gamemode.cfg
  Rules/CommonScripts/MechanismsCommon.as
  Rules/Sandbox/gamemode.cfg
  Rules/TDM/gamemode.cfg
  Scripts/Default/DefaultGUI.as
  Scripts/MapLoaders/LoaderUtilities.as
Labels: change, fix

#2179 Command Quality of Life
  Rules/CommonScripts/ChatCommandCommon.as
  Rules/CommonScripts/ChatCommandManager.as
  Rules/CommonScripts/ChatCommands/BlobCommands.as
  Rules/CommonScripts/ChatCommands/MiscCommands.as
Labels: ready, Sandbox

#2195 [fixed] Saw didn't deactivate when killing a teammate in offline
  Entities/Industry/Saw/Saw.as
Labels: ready, fix

#1898 [fixed] Gold decaying would alert admin (TDM)
  Entities/Common/Decaying/DecayQuantity.as
Labels: ready, fix, TDM

#2145 [fixed] pickup crash
  Entities/Common/Controls/StandardControls.as
  Entities/Common/Controls/StandardPickup.as
Labels: ready, fix
