Repository transhumandesign/kag-base, pull requests merged in 2024-09, with the labels that each got.

#2097 Scoreboard fixes
  Rules/CommonScripts/ScoreboardCommon.as
  Rules/CommonScripts/ScoreboardRender.as
Labels: ready, fix

#1835 Added mugg1991 github contributor accolade
  Rules/CommonScripts/accolade_data.cfg
Labels: no functional change

#1831 Add mapping accolade for Meepo3 (Gix).
  Rules/CommonScripts/accolade_data.cfg
Labels: ready

#2085 [added] Add XionTheDark custom head
  Entities/Characters/Sprites/CustomHeads/XionTheDark.png
Labels: ready

#1851 [changed] Biurza_Tramp_Trap now has gold ores on the right side
  Maps/Official/TDM/Biurza_Tramp_Trap.png
Labels: fix

#1899 Add day time command
  Rules/CommonScripts/ChatCommands.as
  Rules/CommonScripts/ChatCommands.cfg
  Rules/CommonScripts/ChatCommands/MiscCommands.as
  Rules/CommonScripts/DefaultChatCommands.as
Labels: no functional change, ready

#1949 [fixed] Obstructor has proper minimap colors now
  Scripts/MapLoaders/MinimapHook.as
Labels: ready, fix

#1942 [added] "/bot" now allows setting the bot's name
  Rules/CommonScripts/ChatCommands/MiscCommands.as
Labels: no functional change, ready

#1945 [fixed] "/scroll <name>" chat command not working
  Rules/CommonScripts/ChatCommands/BlobCommands.as
Labels: ready, fix

#1935 [fixed] Heal chat command bug
  Rules/CommonScripts/ChatCommands/PlayerCommands.as
Labels: no functional change, ready

#1947 [changed] RumbleGround grain is now positioned in the center
  Maps/Official/TDM/RumbleGround.png
  Maps/RTDM/RumbleGround.png
Labels: change, ready

#1946 [fixed] Dinghy scroll was invisible
  Entities/Items/Scroll/Scroll.png
Labels: ready, fix

#2001 [changed] Seed can be placed on non-static blobs
  Entities/Common/Building/PlacementCommon.as
Labels: no functional change, ready

#2115 fix bomb/arrow cycle with item in hand
  Entities/Common/Controls/StandardControls.as
Labels: ready, fix

#1941 [added] "/seed" chat command can now spawn grain plant, flowers and bush
  Rules/CommonScripts/ChatCommands.cfg
  Rules/CommonScripts/ChatCommands/BlobCommands.as
  Rules/CommonScripts/DefaultChatCommands.as
Labels: no functional change, ready

#2038 [fixed] Bison's or vehicle's damage owner did not get unset when sitting player died
  Entities/Vehicles/Common/Seats.as
Labels: ready, fix

#2026 [fixed] Spiker and Dispenser will work with away-facing Platforms at their exit
  Entities/Structures/Components/Load/Dispenser/Dispenser.as
  Entities/Structures/Components/Load/Dispenser/DispenserFireBlocked.ogg
  Entities/Structures/Components/Load/Spiker/Spiker.as
  Entities/Structures/Platform/PlatformCommon.as
Labels: ready, fix

#1718 Japanese translation recheck
  Locales/Japanese_jp.json
Labels: ready

#1704 Small Fix Russian Locale
  Locales/Russian_ru.json
Labels: ready

#2127 [upd] russian localization
  Locales/Russian_ru.json
Labels: translation
