Repository transhumandesign/kag-base, pull requests merged in 2025-01, with the labels that each got.

#2116 [fixed] localhost building
  Entities/Characters/Builder/BuilderCommon.as
  Entities/Characters/Builder/BuilderInventory.as
  Entities/Characters/Builder/BuilderLogic.as
  Entities/Common/Factory/Shop.as
  Entities/Industry/CTFShops/Quarters/Quarters.as
Labels: ready, fix

#2114 [fix] Tilepos on blob hits being set to 0,0 instead of an actual tilepos
  Entities/Characters/Builder/BuilderLogic.as
Labels: testing needed, ready, fix

#2317 [fix] Material duping
  Entities/Materials/MaterialCommon.as
Labels: fix

#2063 [fixed] fix stun, when you jumping on trampoline
  Entities/Common/Movement/FallDamage.as
Labels: fix

#2165 [fixed] 7 bugs related to filled bucket
  Entities/Items/Bucket/Bucket.as
  Entities/Items/Bucket/Bucket.cfg
Labels: ready

#2185 [fixed] You no longer can take fall damage twice on the same tick
  Entities/Common/Movement/FallDamage.as
Labels: fix

#2288 [fixed] Immunity flashing will stop when losing invincibility
  Entities/Characters/Scripts/UnSpawnImmunity.as
Labels: change

#2263 [fixed] Wood layer was missing when loading wood to a quarry in online
  Entities/Industry/CTFShops/Quarry/Quarry.as
Labels: ready, fix, Sandbox

#2269 [fixed] No flesh gibs when kidssafe is turned on
  Entities/Common/Attacks/FleshHit.as
Labels: change
